### ISSUE TITLE
3D Mil-Std Graphic Labels are misaligned and are condensing on user zoom

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/mil-sym-js#13]
When zooming in on a 3D Mil-Std graphic (Air Corridor), the labels are not aligned, and condense as the user zooms in on the map closer to the graphic. The labels are being condensed into the width of the graphic making them illegible. 
![labelscaling2](https://cloud.githubusercontent.com/assets/25467634/22844731/8f6f09e0-efad-11e6-9b2f-9d1fb821c8ac.png)
![labelscaling1](https://cloud.githubusercontent.com/assets/25467634/22844730/8f69cc00-efad-11e6-8ba8-c414a624e9b2.png)

**Comment by michael-spinelli** [comment]
Which map?

**Comment by alberto-acevedo** [comment]
For the record: Cesium

**Comment by alberto-acevedo** [comment]
Test case:

Use the development branch.

Plot a mil standard air corridor. Set name "label on top"
set altitudeDepth to: 50000,100000
set distance to: 20000

**Comment by mdeutch3** [comment]
Alberto said to disregard this issue.

**Comment by michael-spinelli** [comment]
Closed due to cause being related to using wrong combination of code.

**Comment by Ruck-Over** [comment]
Sorry to revive such an old issue, but I am having the same problem. My slight difference is using KML and 2D instead of 3D.

I have gone through a lot of the emp3 code to see how I may should modify my entity.label and entity.billboard, but have not had success.

Would anybody be able to provide the right combination of code for making these air corridor labels look better in Cesium?
