### ISSUE TITLE
Missing "AM1" 2525C modifiers

### ISSUE THREAD

**Issue by LukashenkoYevhenii** [missioncommand/mil-sym-js#40]
https://github.com/missioncommand/mil-sym-js/blob/master/web/js/src/armyc2/c2sd/renderer/utilities/ModifiersTG.js
Here is exist only AM modifier, but if we looking into 2525c standard on 
TACGRP.FSUPP.ARS.ARATGT.RTGTGT
TACTICAL GRAPHICS
FIRE SUPPORT
AREAS
 AREA TARGET
 RECTANGULAR TARGET
Hierarchy: 2.X.4.3.1.1 

![image](https://user-images.githubusercontent.com/17275749/114161788-1fbf2580-9931-11eb-9403-579068a16c6d.png)

There is exist AM1 modifier

Can you provide info on how to render this type of symbol geometry?

**Comment by michael-spinelli** [comment]
https://github.com/missioncommand/mil-sym-js/wiki/Developer%27s-Guide#33multipoint-symbology

modifiers = {};
modifiers[mtg.AM_DISTANCE] = [300,1000];//AM, AN, & X are the only modifiers that are passed as arrays
modifiers[mtg.AN_AZIMUTH] = [315];	//The rest of the modifiers are String or Number values.
//modifiers[mtg.X_ALTITUDE_DEPTH] = [0];

**Comment by besLisbeth** [comment]
Hi, @michael-spinelli. Can you, please help me with this type of geometry above?
![image](https://user-images.githubusercontent.com/31760858/114402419-78e6bd80-9bac-11eb-9108-a95ac66f6d37.png)
I send to the lib the central point and try to fill in AM modifier with the array of width number and height number and AN modifier with an angle number but got nothing from lib (and no error either). Other types of geometry which I used in my application works fine, so the problem is not in the algorithm but something is wrong with the modifiers or something like that.

Pseudocode: 
```
point: {latitude: 56.757751434928586, longitude: 28.491410377031954}
AM: [250, 250]
AN: 5, also tried [5]
```

**Comment by michael-spinelli** [comment]
You can check the sample here:
http://missioncommand.github.io/mil-sym-js/samples/multiPointTester.html

It's possible your scale is too large or your bounding box is not around the symbol.

I added a another case and was able to get Rectangular Target to render without issue:
[multiPointTester.txt](https://github.com/missioncommand/mil-sym-js/files/6297845/multiPointTester.txt)
