### ISSUE TITLE
Incorrect amplifiers for symbol Air Corridor

### ISSUE THREAD

**Issue by ivanKyka** [missioncommand/mil-sym-js#48]
Hi @michael-spinelli 

When I'm trying to render symbol AirCorridor, I can't set min and max alt by setting amplfiers X and X1 as in standart MIL-STD-2525C. In library that fields defined as H, H1 instead X, X1. Can you set that amplifiers in accordance to standard, or explain me how I can fix that problem?

![image](https://user-images.githubusercontent.com/35963186/186647119-4811ef43-7a30-49c8-8bef-03496bf6524a.png)

**Comment by michael-spinelli** [comment]
It should work.  Are you doing something like this?

var mtg = armyc2.c2sd.renderer.utilities.ModifiersTG;
                modifiers = {};
                modifiers[mtg.AM_DISTANCE] = [1000];
                modifiers[mtg.X_ALTITUDE_DEPTH] = [50,400];

![image](https://user-images.githubusercontent.com/5972575/186681750-5d9d6a82-4b8b-436b-97f2-83107650fe22.png)

**Comment by ivanKyka** [comment]
Thanks for the quick reply!

As I understand, instead using pairt of params (X, X1) I must use X_ALTITUDE_DEPTH with two values into array?

Is it possible to change measure units to meters?

**Comment by michael-spinelli** [comment]
If you set H & H1 instead of using X, you can set the strings to whatever you want and the renderer won't mess with the values.

modifiers[mtg.H_ADDITIONAL_INFO_1] = "50m";
modifiers[mtg.H1_ADDITIONAL_INFO_2] = "400m";

![image](https://user-images.githubusercontent.com/5972575/186735914-f66c9a34-c964-40a2-89a7-693ac8c12684.png)

**Comment by ivanKyka** [comment]
Thanks for you help. I'll try this one
